# 3 модуль - линейная алгебра и Numpy

In [1]:
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    arr1 = X.copy()
    arr2 = X.copy()
    arr2[:,1::2] = a
    print("arr2 = ", arr2)
    arr2[:,::2] = arr2[:,::2]**3
    arr2 = arr2[:,::-1]   
    return np.concatenate((arr1,arr2), axis=1)

In [4]:
x1 = np.array([[100,200,300,400,500],[100,200,300,400,500]])
print(transform(x1,1))

arr2 =  [[100   1 300   1 500]
 [100   1 300   1 500]]
[[      100       200       300       400       500 125000000         1
   27000000         1   1000000]
 [      100       200       300       400       500 125000000         1
   27000000         1   1000000]]


In [5]:
x2 = np.array([[100,200,300,400,500], [1, 2, 4, 5, 6]])
print(transform(x2,1))

arr2 =  [[100   1 300   1 500]
 [  1   1   4   1   6]]
[[      100       200       300       400       500 125000000         1
   27000000         1   1000000]
 [        1         2         4         5         6       216         1
         64         1         1]]


In [6]:
import numpy as np

def encode(a):
    b = np.diff(a)
    #print(b)
    mask = [True,*(b!=0)]
    #print(a[mask])
    #print(len(mask))
    #print(mask)
    #print(b)
    #print(np.array(a))
    #print("___________________")
    ind = np.where(b!=0)[0]
    #print("ind = ",ind)
    
    ind = ind + 1
    #print("ind = ",ind)
    ind = np.insert(ind, 0,0)
    ind = np.append(ind, len(a))
    #print("ind = ",ind)
    return (a[mask], np.diff(ind))

In [11]:
encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))